---
all:
  children:
    dockerbased:
      children:
        storagebox:
          hosts:
            vagrantbox:
              ansible_port: 2222
              ansible_host: 127.0.0.1
              ansible_user: vagrant
              ansible_ssh_private_key_file: "./.vagrant/machines/default/virtualbox/private_key"
              ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
