Vagrant.require_version ">= 1.7.0"
Vagrant.configure(2) do |config|
  config.vm.network "forwarded_port", guest: 80, host: 1080
  config.vm.network "forwarded_port", guest: 443, host: 1443
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  config.vm.provider "virtualbox" do |v|
    v.memory = 8192
    v.cpus = 4
  end

  config.vm.provision "shell", inline: "yum -y install git"
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "/home/nolte/repos-ansible/devops-env/ansible_playbook-baseline-online-server/master-configure-system.yml"
    #ansible.playbook = "../ext_debs/ansible_playbook-baseline-online-server/master-configure-system.yml"
    ansible.galaxy_role_file = "../ext_debs/ansible_playbook-baseline-online-server/requirements.yml"
    ansible.galaxy_roles_path = "/tmp/vagrant_ansible_roles"
    ansible.inventory_path = "../inventory/vagrant"
    ansible.limit = "storagebox"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "../maintenance/master-configure-system.yml"
    ansible.galaxy_role_file = "../maintenance/requirements.yml"
    ansible.galaxy_roles_path = "/tmp/vagrant_ansible_roles"
    ansible.inventory_path = "../inventory/vagrant"
    ansible.limit = "storagebox"
  end

end
