---
repos:
  - repo: 'https://github.com/pre-commit/pre-commit-hooks'
    rev: v2.0.0
    hooks:
      - id: trailing-whitespace
        exclude: |
            (?x)(
                .md|
                .bumpversion.cfg
            )
      - id: end-of-file-fixer
        exclude: ".bumpversion.cfg"
      - id: check-yaml
        exclude: "maintenance/*"
  - repo: 'https://github.com/adrienverge/yamllint'
    rev: v1.16.0
    hooks:
      - id: yamllint
        exclude: "maintenance/*"
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.15.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
