- name: delete tempdir
  file:
    state: absent
    path: "{{ tempfile_certs.path }}"

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted
